default_language_version:
  python: python3.7

exclude: |
  \.usd$
  \.urdf$
  /.*__pycache__/.*
  /.dvc
  /assets

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-case-conflict
      - id: mixed-line-ending

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        args: [--line-length=110]

  - repo: https://github.com/timothycrosley/isort
    rev: 5.11.5
    hooks:
      - id: isort
        args: [--profile=black]
  - repo: https://github.com/PyCQA/flake8
    rev: 5.0.0
    hooks:
      - id: flake8
        args: [--max-line-length=110, --extend-ignore=E402]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.3
    hooks:
      - id: prettier
        types_or: [markdown, yaml, toml, json]
        args: [--print-width=110, --prose-wrap=always]

  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.0
    hooks:
      - id: hadolint
        files: Dockerfile
