# Base pick scenario:
#
# Consist of 4 parts:
# 1. Move_to (find object in env and navigate to it)
# 2. Pick (pick object)
#
# Emulates following test command for behaviour tree:
# msg.tasks = [Task(type="MOVE_TO", object="blue_cube", location="unspecified"),
#              Task(type="PICK_UP", object="blue_cube", location="unspecified"),
#

assets_path: exts/omni.isaac.examples/omni/isaac/examples/virtual-husky/assets &assets_path

scenario:
  - type: MOVE_TO
    object: blue_cube
    location: unspecified

  - type: PICK_UP
    object: blue_cube
    location: unspecified

# Minimal setup for this scenario:
environment:
  # if fixed == true, assume that environment is already set up
  # otherwise, objects will be spawned from the list below
  fixed: false
  objects:
    - type: cube
      name: blue_cube
      has_texture: false
      color: [0, 0, 1]
      position: [2, 0.5, 0.02575]
      orientation: [0, 0, 0, 1]
      scale: [0.0515, 0.0515, 0.0515]
      usd_path: ""
