##################################################################################################
# Конфиг для запуска демо-сценария (QuickStart) и черновик для новых конфигов
# author: Bezuglyj Vitaly
##################################################################################################

# general
logging_level: 'INFO' # 10 #


---
# Background info

background_stage_path: "/background"
use_background: false
use_omni_background: false
background_usd_path: "/Isaac/Environments/Simple_Warehouse/warehouse_with_forklifts.usd" 

---
#Sensors info

tf:
  action_graph_path: "/World/Husky_Robot/TF"

cameras:
  cameras_list: ["zed", "realsense_rear", "realsense_front"] # default list for setup ros publishers
  action_graph_stage_path: "/World/Husky_Robot/ROS_Cameras"

  zed:
    stage_path: "/World/Husky_Robot/fence_link/zed/husky_front_left"
    horizontal_aperture: 5.12
    vertical_aperture: 2.88
    projection_type: "perspective"
    focal_length: 2.733857912
  realsense_rear:
    stage_path: "/World/Husky_Robot/fence_link/realsense/husky_rear_left"
    horizontal_aperture: 3.84
    vertical_aperture: 2.16
    projection_type: "perspective"
    focal_length: 2.731496598
  realsense_front:
    stage_path: "/World/ur5/ur5_ee_link/realsense/husky_front_left"
    horizontal_aperture: 3.84
    vertical_aperture: 2.16
    projection_type: "perspective"
    focal_length: 2.731496598

lidar:
  action_graph_path: "/World/Husky_Robot/LiDAR"
  lidar_stage_path: "/World/Husky_Robot/fence_link/fence_link_small/VLP_16/vlp16/rtx_lidar"
  lidar_model: "VLP_16" # by config name <model>.json

imu:
  action_graph_path: "/World/Husky_Robot/IMU"
  imu_stage_path: "/World/Husky_Robot/base_link/imu"

---
# Navigation info

# navigation_end: [1.4883547, 1.3499106, 0]
# target_position: [-0.3, 0.6, 0,02575] # [2] =  0.0515 / 2.0

trajectory:
  - [2, 2]

# husky_pick_position:
#   - [3, 0.5]

husky_pick_position:
  - [2, 0.5]

husky_place_position:
  - [2, 2.5]


lateral_velocity: 0.5
position_tol: 0.1


---
# Pick and place task info


# pick_position: [2.1, 1.7, 0]
pick_position: [2, 0.5, 0.05]
pick_orientation: [1, 0, 0, 0] # qw, qx, qy, qz
cube_size: [0.0515, 0.0515, 0.0515]
cube_offset: null # Python read it as None


# place_pose: [1.82, 2.95, 0]
place_pose: [2, 2.5, 0.45]


end_effector_offset: [0, 0, 0.033]

# end_effector_offset: [0, 0, 0]


---
# Controllers info

control:
  pick_place:
    # events_dt: [0.005, 0.002, 1, 0.05, 0.01, 0.0005, 0.0008, 0.1, 0.0008, 0.008]
    # events_dt: [0.008, 0.005, 0.1, 0.1, 0.0025, 0.001, 0.0025, 1, 0.008, 0.08] # default
    events_dt: [0.008, 0.005, 0.1, 0.005, 0.0025, 0.003, 0.0025, 1, 0.008, 0.08]
    end_effector_initial_height: 0.76


---
# Robot info

husky_minimal_usd_path: "exts/omni.isaac.examples/omni/isaac/examples/virtual-husky/assets/husky/husky.usd"
# husky_usd_path: "exts/omni.isaac.examples/omni/isaac/examples/virtual-husky/assets/husky/husky_with_sensors.usd"
husky_usd_path: "/home/zhang/.local/share/ov/pkg/isaac_sim-2022.2.1/extension_examples/virtual-husky/asset/husky.usd"
husky_stage_path: "/World/Husky_Robot"
husky_init_pose: [0, 0, 0.15]

wheel_radius: 0.3
wheel_base: 0.5

ur5_usd_path_simple: "exts/omni.isaac.examples/omni/isaac/examples/virtual-husky-2/assets/husky/ur5_with_gripper.usd"
# ur5_usd_path: "exts/omni.isaac.examples/omni/isaac/examples/virtual-husky/assets/husky/ur5_with_gripper_and_cam.usd"
ur5_usd_path: "/home/zhang/.local/share/ov/pkg/isaac_sim-2022.2.1/extension_examples/virtual-husky/asset/ur5_with_gripper.usd" # good
# ur5_usd_path: "/home/zhang/.local/share/ov/pkg/isaac_sim-2022.2.1/extension_examples/virtual-husky-2/asset/ur5_with_gripper.usd"

ur5_stage_path: "/World/ur5"
obj_stage_path: "/World/obj"
end_effector_stage_path: "/World/ur5/robotiq_85_base_link"

connection_joint_stage_path: "/World/connect_joint"
ur5_relative_pose: [0.3312, 0, 0.257]
# joints_default_positions: [1.595672, -2.871760, 2.799204, -3.072348, -1.581982, -0.000120] # Original default joints pose
# joints_default_positions: [3.1415927, -2.871760, 2.799204, -3.072348, -1.581982, -0.000120] # Fixed default joints pose
# joints_default_positions: [0, -1.570, 0, 0, 1.570, 0] # Original default joints pose
joints_default_positions: [0, -0.5, -2, 0, 1.570, 0]
ur5_init_pose: [0, -0.5, -2, 0, 1.570, 0]
---
# Table and container
table_usd_path: "/home/zhang/.local/share/ov/pkg/isaac_sim-2022.2.1/extension_examples/virtual-husky-2/asset/Table_mipt/Table_mipt.usd"
table_position: [2.7, 0.5, 0]
table_orientation: [1, 0, 0, 0]

cub_usd_path: "/home/zhang/.local/share/ov/pkg/isaac_sim-2022.2.1/extension_examples/virtual-husky/asset/cub_fixes1/cub_fixes1.usd"

# trash can -->container
can_usd_path: "/home/zhang/.local/share/ov/pkg/isaac_sim-2022.2.1/extension_examples/virtual-husky/asset/trash_can/can.usd"
can_position: [2, 2.5, 0]
can_orientation: [1, 0, 0, 0]

# Cube with texture
cube_2_usd_path: "/home/zhang/.local/share/ov/pkg/isaac_sim-2022.2.1/extension_examples/virtual-husky/asset/cub_fixes1/cub_fixes1.usd"
cube_2_position: [-0.5, 1.5, 0.4]
cube_2_orientation: [1, 0, 0, 0]

# Opened drawer
drawer_usd_path: "/home/zhang/.local/share/ov/pkg/isaac_sim-2022.2.1/extension_examples/virtual-husky-2/asset/open_drawer/open_drawer.usd"
drawer_position: [2, 2.5, 0]
drawer_orientation: [1, 0, 0, 0]

# Cup
cup_usd_path: "/home/zhang/.local/share/ov/pkg/isaac_sim-2022.2.1/extension_examples/virtual-husky-2/asset/cup/cup.usd"
cup_position: [2, -0.5, 0.11]
cup_orientation: [1, 0, 0, 0]