##################################################################################################
# Конфиг для запуска демо-сценария в фотореалистичной модели 5го этажа МФТИ
# author: Bezuglyj Vitaly
##################################################################################################

# general
logging_level: 'INFO' # 10 #


---
# Background info

background_stage_path: "/background"
use_background: true # If false load simple flat surface (less memory usage)
use_omni_background: false # If true add prefix to path, set false for your own backgrounds
background_usd_path: "" 

---
#Sensors info

tf:
  action_graph_path: "/World/Husky_Robot/TF"

cameras:
  cameras_list: ["zed", "realsense_rear", "realsense_front"] # default list for setup ros publishers
  action_graph_stage_path: "/World/Husky_Robot/ROS_Cameras"

  zed:
    stage_path: "/World/Husky_Robot/fence_link/zed/husky_front_left"
    horizontal_aperture: 5.12
    vertical_aperture: 2.88
    projection_type: "perspective"
    focal_length: 2.733857912
  realsense_rear:
    stage_path: "/World/Husky_Robot/fence_link/realsense/husky_rear_left"
    horizontal_aperture: 3.84
    vertical_aperture: 2.16
    projection_type: "perspective"
    focal_length: 2.731496598
  realsense_front:
    stage_path: "/World/ur5/ur5_ee_link/realsense/husky_front_left"
    horizontal_aperture: 3.84
    vertical_aperture: 2.16
    projection_type: "perspective"
    focal_length: 2.731496598

lidar:
  action_graph_path: "/World/Husky_Robot/LiDAR"
  lidar_stage_path: "/World/Husky_Robot/fence_link/fence_link_small/VLP_16/vlp16/rtx_lidar"
  lidar_model: "VLP_16" # by config name <model>.json

imu:
  action_graph_path: "/World/Husky_Robot/IMU"
  imu_stage_path: "/World/Husky_Robot/base_link/imu"

---
# Navigation info

# navigation_end: [17.34, 0.56, 0]
# target_position: [-0.3, 0.6, 0,02575] # [2] =  0.0515 / 2.0

trajectory:
  - [13.5, 0.07] # Entry to polygon, middle
  - [15.3, 0.13]
  - [14.8, 1.37]
  - [14.7, 2.9]
  - [14.7, 2.9]
  - [16.04, 2.58] # Entry to second room of polygon, middle
  - [17.13, 2.58]
  - [17.34, 0.56]

lateral_velocity: 0.7
position_tol: 0.03


---
# Pick and place task info

target_position: [17.7, 0.7, 0]  # cube position
target_orientation: [1, 0, 0, 0] # qw, qx, qy, qz cube orientation
target_cube_size: [0.0515, 0.0515, 0.0515]
target_cube_offset: null # Python read it as None


husky_target_pose: [17.34, 0.56, 0.02]
end_effector_offset: [0, 0, 0.05]


---
# Controllers info

control:
  pick_place:
    events_dt: [0.005, 0.002, 1, 0.05, 0.0008, 0.005, 0.0008, 0.1, 0.0008, 0.008]
    end_effector_initial_height: 0.6


---
# Robot info

husky_minimal_usd_path: "exts/omni.isaac.examples/omni/isaac/examples/virtual-husky/assets/husky/husky.usd"
husky_usd_path: "exts/omni.isaac.examples/omni/isaac/examples/virtual-husky/assets/husky/husky_with_sensors.usd"
husky_stage_path: "/World/Husky_Robot"
husky_init_pose: [12.0, 0.07, 0.15]

wheel_radius: 0.3
wheel_base: 0.5

ur5_usd_path_simple: "exts/omni.isaac.examples/omni/isaac/examples/virtual-husky/assets/husky/ur5_with_gripper.usd"
ur5_usd_path: "exts/omni.isaac.examples/omni/isaac/examples/virtual-husky/assets/husky/ur5_with_gripper_and_cam.usd"
ur5_stage_path: "/World/ur5"
end_effector_stage_path: "/World/ur5/robotiq_85_base_link"

connection_joint_stage_path: "/World/connect_joint"
ur5_relative_pose: [0.3312, 0, 0.257]
