path_theta_topic: 'path'  
path_mpc_topic: 'mpc_planner/local_path'  #path #/mpc_planner/local_path
path_mpcl4c_topic: 'path_mpcl4c/local_path' 
direction_topic: 'flag_forward'
orient_topic: 'flag_orient'
globla_local_topic: 'flag_global_map'  # if true then this mean we work in global map so there is no narrow 
cmd_topic: 'cmd_vel'
global_frame: 'local_map_lidar'
world_frame: 'local_map_lidar'
base_frame: 'base_link'
odometry_topic: 'lol_odom'
status_topic: 'control_status'
max_v: 0.5
min_v: 0
acc_v: 0.08
max_w: 0.38
acc_w: 0.2
Dist_error_rad: 1.5
upper_limit_v_cmd: 0.3
reduce_max_v_local: 0.04

corner_boundary_1: 0.1
corner_boundary_2: 0.38
corner_boundary_3: 0.7
corner_boundary_4: 1
corner_boundary_5: 1.25

speed_divider_1: 6
speed_divider_2: 3
speed_divider_3: 2
speed_divider_4: 1.5

angle_radution_ratio_1: 1
angle_radution_ratio_2: 0.9
angle_radution_ratio_3: 0.85
angle_radution_ratio_4: 0.8
angle_radution_ratio_5: 0.75
angle_radution_ratio_6: 1

min_v_robot: 0.1
max_start_k_v: 5
correct_orient_at_last_point: false
